name: Get branch test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  get-branch:
    name: Lint PR Name
    #    needs: [ setup_env ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: check version
      run: |
        echo '${{github.ref}}'
    - name: If check
      if: github.ref == 'refs/heads/main'
      run: echo 'made it!'


